export const EVENT = {
  ANIMATION_COMPLETED:    'ANIMATION_COMPLETED',
  BOMB_PLACEMENT_INTENT:  'BOMB_PLACEMENT_INTENT',
  BOMB_DETONATION_INTENT: 'BOMB_DETONATION_INTENT',
  SPAWN_INTENT:           'SPAWN_INTENT',
  PICKED_UP:              'PICKED_UP',
  DAMAGE_FIRE:            'DAMAGE_FIRE',
  DAMAGE_ENEMY:           'DAMAGE_ENEMY',
  SOFT_BLOCK_DESTROYED:   'SOFT_BLOCK_DESTROYED',
  TIMER_EXPIRED:          'TIMER_EXPIRED',
};
